#!/usr/bin/env bash

# Update package lists and upgrade installed packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Install Nginx
sudo apt-get -y install nginx

# Start Nginx service if not already running
if ! systemctl is-active --quiet nginx; then
    sudo service nginx start
fi

# Backup the original Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Define the redirection configuration
redirection_config="\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

# Insert the redirection configuration into the Nginx default site configuration
sudo sed -i "19i $redirection_config" /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
