#!/usr/bin/env bash
#A script that Nginx so that its HTTP response contains a custom
#header (on web-01 and web-02

sudo apt-get -y update
sudo apt-get -y install nginx
#defines custom header
header_value=$(hostname)

echo 'add_header X-Served-By $header_value;' | sudo -a tee /etc/nginx/nginx.conf > /dev/null
service nginx restart
echo "Nginx configured with custom HTTP response header X-Served-By containing the hostname of the server."
