#!/bin/bash

# Variables
MYSQL_USER="root"
NEW_USER="replica_user"
NEW_PASSWORD="rep"
GRANT_USER="holberton_user"

# MySQL commands
MYSQL_CMD="mysql -u $MYSQL_USER -e"

# Create replica_user and grant replication permissions
$MYSQL_CMD "CREATE USER '$NEW_USER'@'%' IDENTIFIED BY '$NEW_PASSWORD';"
$MYSQL_CMD "GRANT REPLICATION SLAVE ON *.* TO '$NEW_USER'@'%';"
$MYSQL_CMD "FLUSH PRIVILEGES;"

# Grant holberton_user SELECT permissions on the mysql.user table
$MYSQL_CMD "GRANT SELECT ON mysql.user TO '$GRANT_USER'@'localhost';"
$MYSQL_CMD "FLUSH PRIVILEGES;"

echo "User $NEW_USER created with replication permissions and $GRANT_USER granted SELECT on mysql.user."
