#!/usr/bin/env bash
#This will have print different ouputs using while loop
i="1"
while [ $i -lt 11 ]; do
	if (( i != 4 )) && (( i != 8 )); then
		echo "Best School"
		i=$((i+1))
	elif (( i == 4 )); then
		echo "Bad luck"
		i=$((i+1))
	else
		echo "Good luck"
		i=$((i+1))
	fi
done
