#!/usr/bin/env bash
#To print the time for 12hrs and 59 minutes
hour="0"
while ((hour < 13)); do
	echo "hour: $hour"
		min="1"
		while ((min < 60)); do
			echo "$min"
			min=$((min+1))

		done
	hour=$((hour+1))
done
