#!/usr/bin/env bash
#A shorter version of the previous task
#!/bin/bash
useradd -r -s /sbin/nologin nginx
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx && service nginx restart
