#!/usr/bin/env bash
#A shorter version of the previous task
useradd -r -s /sbin/nologin nginx
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default
mkdir -p /var/cache/nginx
chown -R nginx:nginx /var/log/nginx /var/cache/nginx
service nginx restart
